hlint src\Strat-commandline\main.hs
hlint src\StratTree\StratTree.hs
hlint src\StratTree\TreeNode.hs
hlint src\StratTree\Trees.hs
hlint src\StratIO\StratIO.hs
hlint src\Strat-web\WebRunner.hs
hlint src\Strat-web\YesodMain.hs
hlint src\Strat-web\GlobalState.hs
hlint src\Strat-web\Session.hs
hlint test\TicTac\TicTac.hs  
hlint test\TicTac\TTParser.hs 
hlint src\Examples\Checkers\Checkers.hs
hlint src\Examples\Checkers\CheckersText.hs
hlint src\Examples\Checkers\CkParser.hs
hlint src\Examples\Checkers\CheckersJson.hs
hlint src\Examples\WIP\Chess\Chess.hs
hlint src\Examples\WIP\Chess\ChessParser.hs
hlint src\GameRunner\GameRunner.hs
hlint test\StratTreeTest.hs
hlint test\TicTacTest.hs 
hlint test\CheckersTest.hs
hlint test\ChessTest.hs