hlint src\main.hs
hlint src\StratTree\StratTree.hs
hlint src\StratTree\StratTreeTest.hs
hlint src\StratTree\TreeNode.hs
hlint src\StratTree\Internal\Trees.hs
hlint src\StratIO\StratIO.hs
hlint src\TicTac\TicTac.hs  
hlint src\TicTac\TicTacTest.hs  
hlint src\Examples\Checkers\Checkers.hs 
hlint test\CheckersTest.hs