name: Strat
version: '0.1.0.0'
synopsis: Haskell Strategy Game Library WIP
description: Please see README.md
category: Strategy game library
author: Mark Nichols
maintainer: marklnichols@gmail.org
copyright: GPL
license: BSD3
github: marklnichols/Haskell-Strategy-Game-AI-WiP
homepage: http://github.com/marklnichols/Haskell-Strategy-Game-AI-WiP#readme
library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  exposed-modules:
  - Strat.StratTree
  - Strat.StratTree.TreeNode
  - Strat.StratIO
  - Strat.StratTree.Trees
  other-modules:
  - Paths_Strat
  dependencies:
  - base
  - containers
  - lens
  - random
  - rosezipper
  - safe
  - mtl
executables:
  strat-exe:
    main: Main.hs
    source-dirs:
    - main/Strat-commandline
    - src
    - src/Examples/Checkers
    - src/Examples/WIP/Chess
    ghc-options:
      - -Wall
    other-modules:
      Checkers
      CheckersJson
      CheckersText
      Chess
      ChessParser
      CkParser
      GameRunner
      Strat.StratIO
      Strat.StratTree
      Strat.StratTree.TreeNode
      Strat.StratTree.Trees
      StratWeb.WebRunner
      StratWeb.YesodMain
    dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - lens
    - mtl
    - parsec
    - random
    - rosezipper
    - safe
    - text
    - vector
    - yesod-static
    - yesod
    - yesod-core
  test-as-exe:
    main: TestSuite.hs
    source-dirs:
    - test
    - src/Examples/Checkers
    - src/Examples/WIP/Chess
    ghc-options: 
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    other-modules:
      Checkers
      CheckersJson
      CheckersTest
      Chess
      ChessParser
      ChessTest
      CkParser
      StratTreeTest
      TicTac.TTGame
      TicTac.TTParser
      TicTacTest
    dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - hspec
    - lens
    - mtl
    - parsec
    - rosezipper
    - safe
    - Strat
    - vector
    
tests:
  StratTreeTest:
    main: TestSuite.hs
    source-dirs:
    - test
    - src/Examples/Checkers
    - src/Examples/WIP/Chess
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    other-modules:
      Checkers
      CheckersJson
      CheckersTest
      Chess
      ChessParser
      ChessTest
      CkParser
      StratTreeTest
      TicTac.TTGame
      TicTac.TTParser
      TicTacTest
    dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - hspec
    - lens
    - mtl
    - parsec
    - rosezipper
    - safe
    - Strat
    - vector
